language: php

php:
  - 7.0
  - 7.1
  - 7.2

before_script:
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar global require hirak/prestissimo
  - php composer.phar install --dev --no-interaction

script:
  - mkdir -p build/logs
  - mkdir -p build/cov
  - php vendor/bin/phpunit -c phpunit.xml.dist

after_script:
  - php vendor/bin/coveralls -v

